# Generated by Django 2.1.7 on 2019-02-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiuba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ST', 'estudiante'), ('PR', 'profesor'), ('AS', 'ayudante'), ('NO', 'no docente')], default='ST', max_length=2),
        ),
    ]
